FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine3.23 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine3.23 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/backend/ZeroAshTools.Backend/ZeroAshTools.Backend.csproj", "src/backend/ZeroAshTools.Backend/"]
RUN dotnet restore "src/backend/ZeroAshTools.Backend/ZeroAshTools.Backend.csproj"
COPY . .
WORKDIR "/src/src/backend/ZeroAshTools.Backend"
RUN dotnet build "./ZeroAshTools.Backend.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ZeroAshTools.Backend.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ZeroAshTools.Backend.dll"]
